### ISSUE TITLE
FileNotFoundError

### ISSUE THREAD

**Issue by ScyllaCharybdis** [Alchez/Discord_Game_Library#1]
> Exception in command 'game'
> Traceback (most recent call last):
>   File "lib/discord/ext/commands/core.py", line 50, in wrapped
>     ret = yield from coro(*args, **kwargs)
>   File "/cogs/game.py", line 22, in game
>     suggestions = get_suggestions(get_all_users(ctx))
>   File "/cogs/game.py", line 310, in get_suggestions
>     game_list = get_games()
>   File "/cogs/game.py", line 246, in get_games
>     games = dataIO.load_json("data/game/games.json")
>   File "/cogs/utils/dataIO.py", line 32, in load_json
>     return self._read_json(filename)
>   File "/cogs/utils/dataIO.py", line 45, in _read_json
>     with open(filename, encoding='utf-8', mode="r") as f:
> FileNotFoundError: [Errno 2] No such file or directory: 'data/game/games.json'
> 
> The above exception was the direct cause of the following exception:
> 
> Traceback (most recent call last):
>   File "lib/discord/ext/commands/bot.py", line 846, in process_commands
>     yield from command.invoke(ctx)
>   File "lib/discord/ext/commands/core.py", line 630, in invoke
>     yield from injected(*ctx.args, **ctx.kwargs)
>   File "lib/discord/ext/commands/core.py", line 54, in wrapped
>     raise CommandInvokeError(e) from e
> discord.ext.commands.errors.CommandInvokeError: Command raised an exception: FileNotFoundError: [Errno 2] No such file or directory: 'data/game/games.json'

also

> Exception in command 'game steamlink'
> Traceback (most recent call last):
>   File "lib/discord/ext/commands/core.py", line 50, in wrapped
>     ret = yield from coro(*args, **kwargs)
>   File "/cogs/game.py", line 190, in steamlink
>     ids = get_steam_ids()
>   File "/cogs/game.py", line 260, in get_steam_ids
>     return dataIO.load_json("data/game/steamids.json")
>   File "/cogs/utils/dataIO.py", line 32, in load_json
>     return self._read_json(filename)
>   File "/cogs/utils/dataIO.py", line 45, in _read_json
>     with open(filename, encoding='utf-8', mode="r") as f:
> FileNotFoundError: [Errno 2] No such file or directory: 'data/game/steamids.json'
> 
> The above exception was the direct cause of the following exception:
> 
> Traceback (most recent call last):
>   File "lib/discord/ext/commands/bot.py", line 846, in process_commands
>     yield from command.invoke(ctx)
>   File "lib/discord/ext/commands/core.py", line 634, in invoke
>     yield from ctx.invoked_subcommand.invoke(ctx)
>   File "lib/discord/ext/commands/core.py", line 374, in invoke
>     yield from injected(*ctx.args, **ctx.kwargs)
>   File "lib/discord/ext/commands/core.py", line 54, in wrapped
>     raise CommandInvokeError(e) from e
> discord.ext.commands.errors.CommandInvokeError: Command raised an exception: FileNotFoundError: [Errno 2] No such file or directory: 'data/game/steamids.json'

**Comment by Alchez** [comment]
@ScyllaCharybdis, I've moved the files around. This should be fixed now.

**Comment by ScyllaCharybdis** [comment]
It worked, but here some problems.

When I first used **game** command it gave this error:
> Exception in command 'game'
> Traceback (most recent call last):
>   File "lib/discord/ext/commands/core.py", line 50, in wrapped
>     ret = yield from coro(*args, **kwargs)
>   File "/cogs/game.py", line 22, in game
>     suggestions = get_suggestions(get_online_users(ctx))
>   File "/cogs/game.py", line 316, in get_suggestions
>     suggestions = set(user_game_list[0]).intersection(*user_game_list[1:])
> TypeError: 'NoneType' object is not iterable
> 
> The above exception was the direct cause of the following exception:
> 
> Traceback (most recent call last):
>   File "lib/discord/ext/commands/bot.py", line 846, in process_commands
>     yield from command.invoke(ctx)
>   File "lib/discord/ext/commands/core.py", line 630, in invoke
>     yield from injected(*ctx.args, **ctx.kwargs)
>   File "lib/discord/ext/commands/core.py", line 54, in wrapped
>     raise CommandInvokeError(e) from e
> discord.ext.commands.errors.CommandInvokeError: Command raised an exception: TypeError: 'NoneType' object is not iterable

I tried again and now i only received this message and no console error:
> You do not have any games, go buy some!

But I already linked my Steam account, so it was suppost to have game already, right?

One more thing, please make the **game list** command to send to DM, I linked my Steam account so i own almost 6k games, you can imagine how was the spam on Discord channel.

Cheers!

**Comment by Alchez** [comment]
Hey @ScyllaCharybdis, I've made some fixes:

1. I've added an error message for when `[p]game` is run with an empty library, so that it doesn't weird out
2. I've changed so when you run `[p]game steamlink`, it also retrieves and sets your Steam library - sorry it didn't use to happen before! O:)
    - If you've already run `[p]game steamlink`, you can simply use `[p]game update` to retrieve your games
3. `[p]game list` should now send messages over DM, so that it doesn't spam your server anymore :)

**Comment by ScyllaCharybdis** [comment]
Awesome no errors so far.

Suggestion to add some other message to the game command instead of saying that there's no game added, like something a command list.
![capturar](https://user-images.githubusercontent.com/3771877/31742795-94b09776-b437-11e7-924f-482a0ae31813.PNG)

**Comment by Alchez** [comment]
Thanks for the suggestion!

I've made the message more useful now, so it should say how you can interact with the cog better.

:)

**Comment by Alchez** [comment]
@ScyllaCharybdis, just wanted to inform you that I've removed keys from all the older commits, so you might need to re-clone/rebase the repo to make it work. Sorry about the inconvenience.
